version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
networks:
  gringotts: